version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn package
  post_build:
    commands:
      - aws lambda update-function-code --function-name main-api --zip-file fileb://lambda.zip --region us-east-1
      - echo Build completed on `date`